# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Phil Chang
tagline:          'A breakdown of me'
description:      'An archive of dives and tries into questions that rise'
url:              http://i.philchang.me
baseurl:          /

author:
  name:           'Phil Chang'
#  url:            

paginate:         5

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
