# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Phil Chang
tagline:          ''
description:      ''
url:              http://philchang.me
baseurl:          /

author:
  name:           'Phil Chang'
#  url:            

paginate:         5

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde

collections:
  projects:
    output: true
    permalink: /projects/:path/
